inputs:
  - name: ci-assets
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git
run:
  path: bin/bash
  args:
    - -exc
    - cd ci-assets
    - git --no-pager log -n 1
