inputs:
  - name: ci-assets
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: bash
  args:
    - -c
    - |
      set -eux
      ls
      ls /
      cd ci-assets
      git --no-pager log -n 1
