inputs:
  - name: ci-assets
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: bash
  args:
    - -c
    - |
      set -eux
      cd ci-assets
      mkdir output
      git --no-pager log -n 1 > output/last_commit.txt
outputs:
  - name: last-commit-message
