inputs:
  - name: ci-assets
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: ci-assets/ci/scripts/last-commit.sh

outputs:
  - name: last-commit-message
