inputs:
  - name: ci-assets
platform: linux
image_resource:
  type: docker-image
  source:
  repository: node
  tag: 6.3.1
run:
  path: bash
  args:
    - -exc
    - cd ci-assets
    - git --no-pager log -n 1
