inputs:
  - name: ci-assets
  - name: scripts
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: ./scripts/last-commit.sh

outputs:
  - name: last-commit-message
