inputs:
  - name: last-commit-message
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: bash
  args:
    - -c
    - |
      set -eux
      cd last-commit-message
      ls
      cat last_commit.txt
