inputs:
  - name: ci-assets
  - name: last-commit-message
  - name: ci-changelog
platform: linux
image_resource:
  type: docker-image
  source:
    # TODO: questionable image choice
    repository: samueldebruyn/debian-git
run:
  path: ci-assets/ci/scripts/update-readme.sh

outputs:
  - name: ci-changelog-update