inputs:
  - name: last-commit-message
  - name: ci-changelog
platform: linux
image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git
run:
  path: bash
  args:
    - -c
    - |
      set -eux
      cd ci-changelog
      cat ../last-commit-message/last-commit.txt | cat - README.md temp && mv temp README.md
      git add README.md
      git commit -m "Updating Changelog"
      git push
