---
resources:
- name: ci-assets
  type: git
  source:
    uri: ((assets-repo))
    branch: master

- name: ci-changelog
  type: git
  source:
    uri: ((changelog-repo))
    branch: master
    username: ((concourse-output-git-user))
    password: ((concourse-output-git-pw))

jobs:
- name: update-changelog
  public: true
  plan:
  - get: ci-assets
    trigger: true
  - get: ci-changelog
  - task: last-commit
    file: ci-assets/ci/tasks/last-commit.yml
  - task: update-readme
    file: ci-assets/ci/tasks/update-readme.yml
    params:
      GIT_USER: ((readme-update-git-user))
      GIT_EMAIL: ((readme-update-git-email))
  - put: ci-changelog
    params:
      repository: ci-changelog-update
