---
resources:
- name: ci-assets
  type: git
  source:
    uri: https://github.com/johnnason/concourse-sandbox.git
    branch: master

- name: ci-changelog
  type: git
  source:
    uri: https://github.com/johnnason/concourse-output.git
    branch: master
    username: johnnason
    password: ((concourse-output-git-pw))

jobs:
- name: update-changelog
  public: true
  plan:
  - get: ci-assets
    trigger: true
  - get: ci-changelog
  - task: last-commit
    file: ci-assets/ci/tasks/last-commit.yml
  - task: update-readme
    file: ci-assets/ci/tasks/update-readme.yml
  - put: ci-changelog
    params:
      repository: ci-changelog-updated
